name: Create release


on: create

jobs:
  tag_filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: 'tag'

  create_release:
    runs-on: ubuntu-latest
    needs: tag_filter
    steps:
    - uses: actions/checkout@master
    - uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
        VERSION_REGEX: "^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"
