name: Create release


on: create

jobs:
  tag_filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      with:
        args: 'tag'

  create_release:
    runs-on: ubuntu-latest
    needs: tag_filter
    steps:
    - uses: actions/checkout@master
    - uses: Roang-zero1/github-create-release-action@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
        VERSION_REGEX: "^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+"
  
  package_linux:
    name: Build + Publish Linux Standalone
    runs-on: ubuntu-latest
    needs: create_release

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        version: 2.4.x

    - name: Set up bundler
      run: gem install bundler

    - name: Build package
      run: script/packages/linux
      env:
        VERSION: ${{github.event.ref}}

    - name: Upload package
      uses: Roang-zero1/github-upload-release-artifacts-action@v2.0.0
      with:
        args: pkg/${{github.event.ref}}/licensed-${{github.event.ref}}-linux-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{secrets.API_AUTH_TOKEN}}

  package_mac:
    name: Build + Publish Mac Standalone
    runs-on: macOS-latest
    needs: create_release

    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        version: 2.4.x
        
    - name: Set up bundler
      run: gem install bundler

    - name: Build package
      run: script/packages/mac
      env:
        VERSION: ${{github.event.ref}}

    - name: Upload package
      uses: Roang-zero1/github-upload-release-artifacts-action@v2.0.0
      with:
        args: pkg/${{github.event.ref}}/licensed-${{github.event.ref}}-darwin-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{secrets.API_AUTH_TOKEN}}
