name: Create release

on: create

jobs:
  tag_filter:
    runs_on: ubuntu-latest
    steps:
    - uses: actions/bin/filter@master
      args: 'tag'

  create_release:
    runs_on: ubuntu-latest
    needs: tag_filter
    steps:
    - uses: Roang-zero1/github-create-release-action@v1.02
      env:
        GITHUB_TOKEN: ${{ secret.API_AUTH_TOKEN }}
        VERSION_REGEX: '^[[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+'
        CHANGELOG_FILE: CHANGELOG.md
